configure.ac: Explicitly depend on gio-unix-2.0
This fixes the following on NixOS:

main_window.c:35:10: fatal error: gio/gdesktopappinfo.h: No such file or directory
   35 | #include <gio/gdesktopappinfo.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

The reason here is the same as https://gitlab.xfce.org/xfce/xfce4-session/-/merge_requests/51,
Here references of GIO_UNIX_CFLAGS already exists but it is never set before this commit.